-- TOY 테이블 생성
CREATE TABLE TOY (
	TOY_NO NUMBER NOT NULL,
	TOY_NAME VARCHAR(20) PRIMARY KEY,
	TOY_STOCK NUMBER DEFAULT 1 CHECK (TOY_STOCK <= 99)
);

DROP TABLE TOY;

-- TOY_CATCH 테이블 생성
CREATE TABLE TOY_CATCH (
	TOY_NAME VARCHAR(20) REFERENCES TOY(TOY_NAME) NOT NULL,
	TOY_STOCK NUMBER DEFAULT 1 CHECK (TOY_STOCK <= 99)
);

DROP TABLE TOY_CATCH;

-- POINT 테이블 생성
CREATE TABLE POINT (POINT NUMBER);

DROP TABLE POINT;

-- TOY 테이블에 사용할 시퀀스 생성
CREATE SEQUENCE SQ_TOY_NO;

DROP SEQUENCE SQ_TOY_NO;

-- TOY 테이블에 샘플 데이터 삽입
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '피카츄', 20);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '안아줘요', 15);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '메타몽', 21);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '춘식이', 9);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '라이언', 6);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '보노보노', 16);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '포로리', 30);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '익명이', 12);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '깨꾹이', 23);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '올쨍이', 20);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '몰랑이', 30);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '파이리', 17);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '꼬부기', 31);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '치코리타', 11);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '김춘배', 22);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '브라운', 12);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '코니', 9);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '샐리', 15);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '오구', 22);
INSERT INTO TOY VALUES (SQ_TOY_NO.NEXTVAL, '몽몽이', 10);

COMMIT;

ROLLBACK;

-- TOY 테이블 데이터 확인
SELECT * FROM TOY;

-- POINT 테이블에 100P 넣어주기
INSERT INTO POINT VALUES (100);

SELECT * FROM POINT;

COMMIT;

ROLLBACK;

-- SHIFT + ALT + A : 세로 블록 선택 가능

-- POINT 테이블에 100P 더해주기
UPDATE POINT SET POINT = POINT + 100;

COMMIT;

ROLLBACK;

-- POINT 테이블 조회
SELECT * FROM POINT;

-- TOY 테이블에서 인형 이름만 조회
SELECT TOY_NAME FROM TOY;

-- 뽑은 인형 목록 보기
SELECT * FROM TOY_CATCH;